%% Initializing
clc; close all;
restoredefaultpath;   % Reset the path to the default state
clear;

% Setup paths based on operating system
switch filesep
    case '\'
        disp('MATLAB is running on Windows.');
        main_folder = 'C:\Data\DCM validation\two column EEG DCM';
        spm_path = 'C:\Toolbox\spm12';
        addpath(spm_path);
        spm;  % Start SPM
        close all;  % Close SPM GUI
        spm('defaults', 'EEG');
    case '/'
        disp('MATLAB is running on Linux.');
        main_folder = '/mnt/scratch2/users/aasadpour/DCM validation/two column EEG DCM';
        jobStorageLocation = '/users/aasadpour/ParallelJobStorage/';
        spm_path = '/users/aasadpour/spm12';        
        addpath(spm_path);
        spm;  % Start SPM
        close all;  % Close SPM GUI
        spm('defaults', 'EEG');
        % Setup parallel computing environment
        poolobj = gcp('nocreate');  % Do not create a new pool if it already exists
        if ~isempty(poolobj)
            delete(poolobj);  % Delete existing parallel pool to restart
        end
        existingProfiles = parallel.clusterProfiles();
        profileName = existingProfiles{1};
        numWorkers = 40;  % Adjust this number based on your hardware capabilities
        matlabRoot = matlabroot;     
        modifyCustomParallelProfile(profileName, numWorkers, matlabRoot, jobStorageLocation);
        parpool(profileName, numWorkers);
end

% Simulation parameters
num_trials = 1000;
fs = 1000;  % Sampling frequency
decision_boundary = 0.25;
a_values = 0.10:0.05:0.7;  % Range of parameter values

% File location for saving data
data_filename = fullfile(main_folder, 'simulated_data.mat');

% Generate data only if it does not exist
if ~exist(data_filename, 'file')
    disp('Generating new data...');
    for i = 1:length(a_values)
        [acc(i), decision_reaction_times, error_reaction_times, decision_trial_indices, error_trial_indices, non_decision_trial_indices, ...
        o1_e1, o1_e2, o1_i1, o2_e1, o2_e2, o2_i1, input_1, input_2, avg_decision_rts(i), avg_error_rts(i), output1_LFP, output2_LFP, ...
        output1_EEG, output2_EEG] = fsm3(num_trials, fs, decision_boundary, a_values(i));

        % Store trial data in structures
        correct_trials{i} = struct('input1', input_1(decision_trial_indices,:), ...
                                   'input2', input_2(decision_trial_indices,:), ...
                                   'output1_e1', o1_e1(decision_trial_indices,:), ...
                                   'output1_e2', o1_e2(decision_trial_indices,:), ...
                                   'output1_i1', o1_i1(decision_trial_indices,:), ...
                                   'output2_e1', o2_e1(decision_trial_indices,:), ...
                                   'output2_e2', o2_e2(decision_trial_indices,:), ...
                                   'output2_i1', o2_i1(decision_trial_indices,:), ...
                                   'output1_LFP', output1_LFP(decision_trial_indices,:), ...
                                   'output2_LFP', output2_LFP(decision_trial_indices,:), ...
                                   'output1_EEG', output1_EEG(decision_trial_indices,:), ...
                                   'output2_EEG', output2_EEG(decision_trial_indices,:), ...
                                   'reaction_times', decision_reaction_times);
        
        error_trials{i} = struct('input1', input_1(error_trial_indices,:), ...
                                   'input2', input_2(error_trial_indices,:), ...
                                   'output1_e1', o1_e1(error_trial_indices,:), ...
                                   'output1_e2', o1_e2(error_trial_indices,:), ...
                                   'output1_i1', o1_i1(error_trial_indices,:), ...
                                   'output2_e1', o2_e1(error_trial_indices,:), ...
                                   'output2_e2', o2_e2(error_trial_indices,:), ...
                                   'output2_i1', o2_i1(error_trial_indices,:), ...
                                   'output1_LFP', output1_LFP(error_trial_indices,:), ...
                                   'output2_LFP', output2_LFP(error_trial_indices,:), ...
                                   'output1_EEG', output1_EEG(error_trial_indices,:), ...
                                   'output2_EEG', output2_EEG(error_trial_indices,:), ...
                                   'reaction_times', error_reaction_times);
        
        non_decision_trials{i} = struct('input1', input_1(non_decision_trial_indices,:), ...
                                   'input2', input_2(non_decision_trial_indices,:), ...
                                   'output1_e1', o1_e1(non_decision_trial_indices,:), ...
                                   'output1_e2', o1_e2(non_decision_trial_indices,:), ...
                                   'output1_i1', o1_i1(non_decision_trial_indices,:), ...
                                   'output2_e1', o2_e1(non_decision_trial_indices,:), ...
                                   'output2_e2', o2_e2(non_decision_trial_indices,:), ...
                                   'output2_i1', o2_i1(non_decision_trial_indices,:), ...
                                   'output1_LFP', output1_LFP(non_decision_trial_indices,:), ...
                                   'output2_LFP', output2_LFP(non_decision_trial_indices,:), ...
                                   'output1_EEG', output1_EEG(non_decision_trial_indices,:), ...
                                   'output2_EEG', output2_EEG(non_decision_trial_indices,:));
    end
    
    % Create directory if it does not exist
    if ~exist(main_folder, 'dir')
        mkdir(main_folder);
    end
    
    % Save all generated data
    save(data_filename, 'correct_trials', 'error_trials', 'non_decision_trials', '-v7.3');
else
    disp('Data file already exists. Loading data for further processing...');
end

% Load and proceed with DCM estimation
response_type = 'correct_trials';
load(data_filename, response_type);  % Load correct trials for DCM analysis
down_sample = 1;
estimate_dcm_for_erp(correct_trials{2}, fs, main_folder, response_type, down_sample);

% Additional analysis can be uncommented and used as required
% plot_analysis(a_values, acc, avg_decision_rts, avg_error_rts);
